package idproject;
import com.google.zxing.BarcodeFormat;
import java.awt.BorderLayout;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.util.HashMap;
import java.util.Map;

public class home extends javax.swing.JFrame {
    
    public String lastName = " ";
    public String firstName = " ";
    public String idNumber = " ";
    public String course = " ";
    public String yearLevelStr = " ";
    public int yearLevel = 0;

    /**
     * Creates new form home
     */
    
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        access = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        inputFirstName = new javax.swing.JTextField();
        first = new javax.swing.JLabel();
        inputCourse = new javax.swing.JTextField();
        year = new javax.swing.JLabel();
        inputIdNumber = new javax.swing.JTextField();
        program = new javax.swing.JLabel();
        inputYearLevel = new javax.swing.JTextField();
        IdNumber = new javax.swing.JLabel();
        inputLastName = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        access.setBackground(new java.awt.Color(255, 255, 255));
        access.setForeground(new java.awt.Color(255, 255, 255));
        access.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 6, 159));
        jLabel1.setText("QR CARD");
        access.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        LastName.setBackground(new java.awt.Color(16, 6, 159));
        LastName.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        LastName.setForeground(new java.awt.Color(16, 6, 159));
        LastName.setText("LAST NAME:");
        access.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        inputFirstName.setBackground(new java.awt.Color(255, 255, 255));
        inputFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFirstNameActionPerformed(evt);
            }
        });
        inputFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputFirstNameKeyTyped(evt);
            }
        });
        access.add(inputFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 210, -1));

        first.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        first.setForeground(new java.awt.Color(16, 6, 159));
        first.setText("FIRST NAME:");
        access.add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        inputCourse.setBackground(new java.awt.Color(255, 255, 255));
        inputCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCourseActionPerformed(evt);
            }
        });
        inputCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputCourseKeyTyped(evt);
            }
        });
        access.add(inputCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 210, -1));

        year.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        year.setForeground(new java.awt.Color(16, 6, 159));
        year.setText("YEAR LEVEL:");
        access.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        inputIdNumber.setBackground(new java.awt.Color(255, 255, 255));
        inputIdNumber.setForeground(new java.awt.Color(0, 0, 0));
        inputIdNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdNumberActionPerformed(evt);
            }
        });
        inputIdNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputIdNumberKeyTyped(evt);
            }
        });
        access.add(inputIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 210, -1));

        program.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        program.setForeground(new java.awt.Color(16, 6, 159));
        program.setText("COURSE:");
        access.add(program, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        inputYearLevel.setBackground(new java.awt.Color(255, 255, 255));
        inputYearLevel.setForeground(new java.awt.Color(0, 0, 0));
        inputYearLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputYearLevelKeyPressed(evt);
            }
        });
        access.add(inputYearLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 210, -1));

        IdNumber.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        IdNumber.setForeground(new java.awt.Color(16, 6, 159));
        IdNumber.setText("ID NUMBER:");
        access.add(IdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        inputLastName.setBackground(new java.awt.Color(255, 255, 255));
        inputLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLastNameActionPerformed(evt);
            }
        });
        inputLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputLastNameKeyTyped(evt);
            }
        });
        access.add(inputLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 210, -1));

        create.setBackground(new java.awt.Color(16, 6, 159));
        create.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("CREATE");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                createMousePressed(evt);
            }
        });
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        create.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createKeyTyped(evt);
            }
        });
        access.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, 30));

        clear.setBackground(new java.awt.Color(16, 5, 169));
        clear.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clearMousePressed(evt);
            }
        });
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        access.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 100, 30));

        jButton3.setBackground(new java.awt.Color(5, 16, 169));
        jButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ACCESS");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        access.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 100, 30));

        getContentPane().add(access, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 500));

        jPanel2.setBackground(new java.awt.Color(16, 6, 159));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/ICONS BG.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ICONS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(191, 191, 191))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 470, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFirstNameActionPerformed
              
    }//GEN-LAST:event_inputFirstNameActionPerformed

    private void inputLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLastNameActionPerformed
              
    }//GEN-LAST:event_inputLastNameActionPerformed

    private void inputLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputLastNameKeyTyped
          
    }//GEN-LAST:event_inputLastNameKeyTyped

    private void inputIdNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdNumberActionPerformed
        
    }//GEN-LAST:event_inputIdNumberActionPerformed

    private void inputIdNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputIdNumberKeyTyped
          
    }//GEN-LAST:event_inputIdNumberKeyTyped

    private void inputFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFirstNameKeyTyped
            
    }//GEN-LAST:event_inputFirstNameKeyTyped

    private void inputCourseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputCourseKeyTyped
        
    }//GEN-LAST:event_inputCourseKeyTyped

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        JOptionPane.showMessageDialog(this, "ID Created!");
    }//GEN-LAST:event_createActionPerformed

    private void inputYearLevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputYearLevelKeyPressed
       
    }//GEN-LAST:event_inputYearLevelKeyPressed

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked

    }//GEN-LAST:event_createMouseClicked

    private void createKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createKeyTyped
        
    }//GEN-LAST:event_createKeyTyped

    private void createMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMousePressed

        idNumber = inputIdNumber.getText();       
        lastName = inputLastName.getText(); 
        firstName = inputFirstName.getText();   
        yearLevelStr = inputYearLevel.getText();
        course = inputCourse.getText();
       
        try {
            yearLevel = Integer.parseInt(yearLevelStr);
        } catch (NumberFormatException e) {
            e.printStackTrace();
            return;
        }
         
        String userInputString = "ID: " + idNumber + "\nLast Name: " + lastName +
        "\nFirst Name: " + firstName + "\nYear Level: " + yearLevel +
        "\nCourse: " + course;
        String filePath = "C:\\Users\\candi\\Documents\\ID\\" + lastName + "QRCode.png";
             
        Map<EncodeHintType, Object> hintMap = new HashMap<>();
        hintMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
        hintMap.put(EncodeHintType.MARGIN, 1);
        hintMap.put(EncodeHintType.CHARACTER_SET, "UTF-8");

        try {
            int size = 300; // QR code size
            BitMatrix bitMatrix = new MultiFormatWriter().encode(userInputString, BarcodeFormat.QR_CODE, size, size, hintMap);
        } catch (WriterException e) {
            e.printStackTrace();
            // Handle WriterException if needed
        }
        QRCodeImageWriter.generateAndSaveQRCode(userInputString, filePath);
        IDCardCRUD.createStudent(idNumber, lastName, firstName, yearLevel, course);
    }//GEN-LAST:event_createMousePressed

    private void clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMousePressed
         inputFirstName.setText(" ");
         inputCourse.setText(" ");
         inputIdNumber.setText(" ");
         inputYearLevel.setText(" ");
         inputLastName.setText(" "); 
    }//GEN-LAST:event_clearMousePressed

    private void inputCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCourseActionPerformed
       
    }//GEN-LAST:event_inputCourseActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       
    }//GEN-LAST:event_clearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        JPanel panel = new JPanel(new BorderLayout());
        JPasswordField passwordField = new JPasswordField();
        panel.add(new JLabel("Enter Password:"), BorderLayout.NORTH);
        panel.add(passwordField, BorderLayout.CENTER);

        ImageIcon icon = new ImageIcon("\"C:\\Users\\candi\\Downloads\\ICONS BG.png\"");
        JLabel iconLabel = new JLabel(icon);
        panel.add(iconLabel, BorderLayout.WEST);

        int option = JOptionPane.showConfirmDialog(
        null,
        panel,
        "Password Required",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );
    
        if (option == JOptionPane.OK_OPTION) {
            char[] enteredPassword = passwordField.getPassword();
            char[] correctPassword = "user29".toCharArray();
        
        if (Arrays.equals(enteredPassword, correctPassword)) {
             List<Student> students = IDCardCRUD.readStudents();
             StudentTableDisplay display = new StudentTableDisplay(students);
             display.setVisible(true);
        } else {
                JOptionPane.showMessageDialog(null, "Incorrect Password. Access Denied.", "Error", JOptionPane.ERROR_MESSAGE);
        }
            Arrays.fill(enteredPassword, ' ');
        } else {
            JOptionPane.showMessageDialog(null, "Password input canceled. Access Denied.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3MousePressed


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdNumber;
    private javax.swing.JLabel LastName;
    private javax.swing.JPanel access;
    private javax.swing.JButton clear;
    private javax.swing.JButton create;
    private javax.swing.JLabel first;
    private javax.swing.JTextField inputCourse;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputIdNumber;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JTextField inputYearLevel;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel program;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables

}